### ISSUE TITLE
requirements.txt ist missing in Pypi's SDIST source

### ISSUE THREAD

**Issue by onkelbeh** [bjornorri/pysaltbox#6]
Hi,

I hope you don't mind I am using your component in [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository).

I am not using your component myself, but I maintain the [Ebuilds for it](https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/saltbox) for completeness.
During compile test a saw that your component cannot be compiled from source, because requirements.txt ist missing in Pypi's SDIST source. Please update your build process to copy this required file. Or, at least, pin version tags here. I could also use githubs source archives, but Pypi SDIST would be preferred.

Glad, this avoids a lot of patching out your old and hardly pinned requirements.
instead of the already prepared patch routine:

```bash
src_prepare() {
              sed "s/beautifulsoup4==4.8.2/beautifulsoup4/g" -i requirements.txt || die
              sed "s/certifi==2019.11.28/certifi/g" -i requirements.txt || die
              sed "s/chardet==3.0.4/chardet/g" -i requirements.txt || die
              sed "s/idna==2.8/idna/g" -i requirements.txt || die
              sed "s/requests==2.22.0/requests/g" -i requirements.txt || die
              sed "s/soupsieve==1.9.5/soupsieve/g" -i requirements.txt || die
              sed "s/urllib3==1.25.7/urllib3/g" -i requirements.txt || die
              eapply_user
}
```

I just did a:
```bash
src_prepare() {
              echo "beautifulsoup4" > requirements.txt
              echo "certifi" >> requirements.txt
              echo "chardet" >> requirements.txt
              echo "idna" >> requirements.txt
              echo "requests" >> requirements.txt
              echo "soupsieve" >> requirements.txt
              echo "urllib3" >> requirements.txt
              eapply_user
}
```

My current patch: https://github.com/onkelbeh/HomeAssistantRepository/commit/d800cab608ccf094f6dc1a1366a888dc5c34af62

As MartinHjelmare already explained: To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.
Thanks.

**Comment by bjornorri** [comment]
Closing since the integration is not a part of Home Assistant anymore.
